# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interfaces\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(509, 123)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.subarea_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.subarea_lineEdit.setGeometry(QtCore.QRect(10, 10, 351, 22))
        self.subarea_lineEdit.setObjectName("subarea_lineEdit")
        self.open_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.open_pushButton.setGeometry(QtCore.QRect(370, 10, 121, 24))
        self.open_pushButton.setObjectName("open_pushButton")
        self.start_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.start_pushButton.setGeometry(QtCore.QRect(370, 40, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.start_pushButton.setFont(font)
        self.start_pushButton.setObjectName("start_pushButton")
        self.datos_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.datos_pushButton.setGeometry(QtCore.QRect(100, 40, 81, 41))
        self.datos_pushButton.setObjectName("datos_pushButton")
        self.sigs_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.sigs_pushButton.setGeometry(QtCore.QRect(10, 40, 81, 41))
        self.sigs_pushButton.setObjectName("sigs_pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 90, 201, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(247, 90, 241, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(310, 50, 51, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 50, 91, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cycle Calculator"))
        self.open_pushButton.setText(_translate("MainWindow", "Subarea Folder"))
        self.start_pushButton.setText(_translate("MainWindow", "START"))
        self.datos_pushButton.setText(_translate("MainWindow", "Create Datos"))
        self.sigs_pushButton.setText(_translate("MainWindow", "Create Sigs"))
        self.label.setText(_translate("MainWindow", "Credits: Nakamura"))
        self.lineEdit.setText(_translate("MainWindow", "0.80"))
        self.label_2.setText(_translate("MainWindow", "Máx. Relation:"))